all: pdf

pdf: slides.tex question_bank.tex timeline.tex leaderboard_llm_human.tex leaderboard_llm.tex leaderboard_llm_human_combo.tex
	pdflatex slides.tex

clean:
	rm -f slides.aux slides.log slides.nav slides.snm slides.toc slides.out slides.pdf

