# The onboard CLI is run locally by an admin; it is not deployed to GCP.
# This Makefile exists so that `make setup-python-env` installs requirements.txt
# and the root `make clean` can recurse into this directory.

.PHONY: all clean

all:
	@:

clean:
	rm -rf __pycache__
