FROM REGION-docker.pkg.dev/serverless-runtimes/STACK/runtimes/PYTHON_VERSION

RUN whoami || echo "whoami not found"

USER root
RUN apt-get update && apt-get install -y git openssh-client
USER www-data

COPY . /app

WORKDIR /app

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "main.py"]
