#!/usr/bin/env python3
"""Add relative-return pairs to the list at the end of src/sources/yfinance_questions.py.

When to use: once to create the pair pool, and again whenever we want more pairs (for example
after the S&P 500 changes). Why a script: the pair selection is a research decision, so the
list lives in git and is reviewed as a diff instead of being drawn at runtime.

The universe is every active single ticker in the yfinance question bank that has a business
summary and is in the S&P 500 today, minus nullified tickers, with renamed originals swapped for
their replacement symbol. Only the generated block below the module's marker line is rewritten; the functions
above it are left alone. Pairs already in the module are kept in place; new pairs are appended
until the module holds --target pairs. Rerunning with the same target changes nothing.

Usage:
    python scripts/generate_yfinance_pairs.py --question-file /path/to/yfinance_questions.jsonl
    python scripts/generate_yfinance_pairs.py --question-file ... --target 1200

The question file is `yfinance_questions.jsonl` from the question bank bucket (or a local
mirror of it). Run from the repo root.
"""

import argparse
import itertools
import json
import random
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from helpers.yfinance import is_pair_id  # noqa: E402
from sources import yfinance_questions  # noqa: E402
from sources._metadata import SOURCE_METADATA  # noqa: E402

MODULE_PATH = ROOT / "src" / "sources" / "yfinance_questions.py"
DEFAULT_TARGET = 1000
DEFAULT_SEED = 20261002


def read_pool(question_file: Path) -> set[str]:
    """Return the active single tickers in the yfinance question file that have a summary.

    A ticker whose background is "N/A" has no business summary on Yahoo, so a pair naming it
    would have none either; it is left out.
    """
    pool = set()
    with open(question_file, encoding="utf-8") as f:
        for line in f:
            row = json.loads(line)
            if not row["resolved"] and not is_pair_id(row["id"]) and row["background"] != "N/A":
                pool.add(row["id"])
    return pool


def build_universe(
    pool: set[str], sp500: list[str], nullified_ids: set[str], ticker_renames: list[dict]
) -> list[str]:
    """Return the sorted tickers eligible for new pairs.

    Renamed originals are swapped for their replacement symbol before the index check, because
    Wikipedia lists the current symbol.

    Args:
        pool (set[str]): Active single tickers from the question file.
        sp500 (list[str]): Current S&P 500 constituent symbols.
        nullified_ids (set[str]): Question ids that are nullified and must be excluded.
        ticker_renames (list[dict]): Dicts with `original_ticker` and `replacement_ticker`.
    """
    replacements = {r["original_ticker"]: r["replacement_ticker"] for r in ticker_renames}
    in_index = set(sp500)
    universe = set()
    for ticker in pool:
        if ticker in nullified_ids:
            continue
        ticker = replacements.get(ticker, ticker)
        if ticker in in_index:
            universe.add(ticker)
    return sorted(universe)


def draw_pairs(
    universe: list[str], existing: list[tuple[str, str]], target: int, seed: int
) -> list[tuple[str, str]]:
    """Return ``existing`` followed by newly drawn pairs, ``target`` pairs in all.

    Each new pair's orientation is random; a pair is never drawn again in either order. Exits
    with an error when the universe cannot supply enough new pairs.

    Args:
        universe (list[str]): Tickers eligible for pairing.
        existing (list[tuple[str, str]]): Pairs already in the module; kept first and in order.
        target (int): Total number of pairs wanted, existing pairs included.
        seed (int): Seed for the random draw of the new pairs.
    """
    existing_set = {tuple(sorted(p)) for p in existing}
    candidates = [p for p in itertools.combinations(sorted(universe), 2) if p not in existing_set]
    n_new = max(0, target - len(existing))
    if n_new > len(candidates):
        sys.exit(
            f"Need {n_new} new pairs but the universe of {len(universe)} tickers only offers "
            f"{len(candidates)} unused pairs."
        )
    rng = random.Random(seed)
    new = sorted(rng.sample(candidates, n_new))
    # Random orientation. Otherwise X is always the alphabetically-first ticker, so "Yes" always
    # means the earlier letter wins and a yes-leaning forecaster gets a systematic edge.
    new = [(y, x) if rng.random() < 0.5 else (x, y) for x, y in new]
    return list(existing) + new


GENERATED_MARKER = (
    "# --- Generated by scripts/generate_yfinance_pairs.py; do not edit below this line ---"
)


def render_pairs_block(
    pairs: list[tuple[str, str]], seed: int, universe_size: int, today: str
) -> str:
    """Return the generated part of yfinance_questions.py: marker, provenance line and the list.

    Args:
        pairs (list[tuple[str, str]]): Every pair the module should hold, in order.
        seed (int): Seed used for the newly drawn pairs.
        universe_size (int): Number of tickers that were eligible.
        today (str): ISO date of this run.
    """
    body = "".join(f'    ("{x}", "{y}"),\n' for x, y in pairs)
    return (
        f"{GENERATED_MARKER}\n"
        f"# Last generated {today} with seed {seed} from a universe of {universe_size} tickers.\n"
        "YFINANCE_PAIRS: list[tuple[str, str]] = [\n" + body + "]\n"
    )


def replace_pairs_block(module_text: str, block: str) -> str:
    """Return the module with everything from the marker line on replaced by ``block``.

    The hand-written part above the marker is left untouched. A module with no marker yet gets
    the block appended.

    Args:
        module_text (str): Current source of yfinance_questions.py.
        block (str): Output of ``render_pairs_block``.
    """
    if GENERATED_MARKER in module_text:
        return module_text[: module_text.index(GENERATED_MARKER)] + block
    return module_text.rstrip("\n") + "\n\n\n" + block


def main() -> None:
    """Parse arguments, draw pairs, and rewrite the module."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--question-file",
        type=Path,
        required=True,
        help="yfinance_questions.jsonl from the question bank bucket, or a local mirror of it.",
    )
    parser.add_argument(
        "--target",
        type=int,
        default=DEFAULT_TARGET,
        help="Total number of pairs the module holds after the run, existing pairs included "
        "(default: %(default)s).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help="Seed for drawing new pairs; existing pairs are never redrawn "
        "(default: %(default)s).",
    )
    args = parser.parse_args()
    if not args.question_file.is_file():
        sys.exit(f"No such question file: {args.question_file}")

    # Heavy import (yfinance, pandera); only needed for the live scrape.
    from sources.yfinance import YfinanceSource

    sp500 = YfinanceSource._get_sp500_tickers()
    if not sp500:
        sys.exit("Could not scrape the S&P 500 constituents from Wikipedia. Nothing written.")

    meta = SOURCE_METADATA["yfinance"]
    pool = read_pool(args.question_file)
    universe = build_universe(
        pool=pool,
        sp500=sp500,
        nullified_ids={nq.id for nq in meta["nullified_questions"]},
        ticker_renames=meta["ticker_renames"],
    )
    existing = list(yfinance_questions.YFINANCE_PAIRS)
    pairs = draw_pairs(universe, existing, target=args.target, seed=args.seed)
    if len(pairs) == len(existing):
        print("No new pairs to add; module unchanged.")
        return

    block = render_pairs_block(
        pairs, seed=args.seed, universe_size=len(universe), today=str(date.today())
    )
    MODULE_PATH.write_text(replace_pairs_block(MODULE_PATH.read_text(), block))
    print(f"pool {len(pool)} tickers, universe {len(universe)} tickers")
    print(f"kept {len(existing)} pairs, added {len(pairs) - len(existing)}, wrote {MODULE_PATH}")


if __name__ == "__main__":
    main()
