name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: make setup-python-env

    - name: Run lint
      run: |
        . .venv/bin/activate
        make lint MAKE_LINT_ERROR_OUT=1

    - name: Run tests
      run: make test
